name: t
version: 1.0.0
synopsis: A turbo-useless templating library
description: See README.markdown
category: Text
maintainer: matvey.aksenov@gmail.com
copyright: Matvey Aksenov 2022
license: BSD2
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown
github: supki/t

dependencies:
  - base >= 4.14 && < 5

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - TypeOperators

library:
  dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - either
    - hashable
    - mtl
    - parsers
    - pcre-light
    - scientific
    - text
    - transformers
    - trifecta
    - unordered-containers
    - vector
  source-dirs:
    src
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    # - -Werror

executables:
  t:
    dependencies:
      - t
      - aeson
      - text
    source-dirs:
      driver
    main:
      Main.hs
    ghc-options:
      - -Wall
      # - -Werror
      - -threaded
      - -with-rtsopts=-N

tests:
  spec:
    dependencies:
      - t
      - aeson
      - aeson-qq
      - bytestring
      - hspec
      - scientific
      - text
      - unordered-containers
      - vector
    source-dirs:
      test
    main:
      Spec.hs
    ghc-options:
      - -Wall
      # - -Werror
      - -threaded
      - -with-rtsopts=-N
