name: t
version: 1.0.0
synopsis: A turbo-useless templating library
description: See README.markdown
category: Text
maintainer: matvey.aksenov@gmail.com
copyright: Matvey Aksenov 2022
license: BSD2
extra-doc-files:
  - README.markdown
  - CHANGELOG.markdown
github: supki/t
tested-with:
  - GHC==9.6.4 # it's actually 9.6.5, but that version is unknown to my haskell-ci
  - GHC==9.8.2

custom-setup:
  dependencies:
    # 4.18 comes with GHC 9.6
    - base >= 4.18 && < 5
    # 3.10 comes with GHC 9.6
    - Cabal >= 3.10 && < 3.11
    - directory
    - filepath
    - process

dependencies:
  - base >= 4.18 && < 5

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - OverloadedStrings
  - TypeOperators

library:
  dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - directory
    - either
    - filepath
    - hashable
    - haskeline
    - mtl
    - parsers
    - pcre-light
    - prettyprinter
    - prettyprinter-ansi-terminal
    - scientific
    - temporary
    - text
    - transformers
    - trifecta
    - unordered-containers
    - vector
  source-dirs:
    src
  generated-exposed-modules:
    Meta_t
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Wno-incomplete-uni-patterns
    # - -Werror

executables:
  t:
    dependencies:
      - t
      - aeson
      - filepath
      - directory
      - optparse-applicative
    source-dirs:
      driver
    main:
      Main.hs
    ghc-options:
      - -Wall
      - -Wno-incomplete-uni-patterns
      # - -Werror
      - -threaded
      - -with-rtsopts=-N

tests:
  spec:
    build-tools:
      - hspec-discover
    dependencies:
      - t
      - aeson
      - aeson-qq
      - bytestring
      - hspec
      - pcre-light
      - scientific
      - text
      - unordered-containers
      - vector
    source-dirs:
      test
    main:
      Spec.hs
    ghc-options:
      - -Wall
      - -Wno-incomplete-uni-patterns
      # - -Werror
      - -threaded
      - -with-rtsopts=-N
